### ISSUE TITLE
how to use Misc Cheats

### ISSUE THREAD

**Issue by renwushibie** [Aidanamite/Misc-Cheats#3]
Hello, I would like to know how to use your Misc Cheats module, I have pressed a lot of keys in raftmodding software, but there is no menu bar.

**Comment by Aidanamite** [comment]
have you read the mod page at all?

**Comment by renwushibie** [comment]
> 你读过国防部的页面吗？

Finished reading, I also downloaded the api module, but I entered the game and pressed all the buttons, but I did not see where to activate your module

**Comment by Aidanamite** [comment]
have you loaded the mods in the mod manager?

**Comment by renwushibie** [comment]
> 你在mod管理器中加载mods了吗？

yes

**Comment by Aidanamite** [comment]
is there a "mods" tab in the game settings?

**Comment by renwushibie** [comment]
> is there a "mods" tab in the game settings?

Thank you. I found it. It's my fault
